/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 PyramidTextured.glb --transform 
Files: PyramidTextured.glb [668.38KB] > D:\_Code projects\marcomuseum\public\models\PyramidTextured-transformed.glb [130.51KB] (80%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/PyramidTextured-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={31.515}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.Brick} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials.Sand} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials.Floor} />
        <mesh geometry={nodes.Cube001_3.geometry} material={materials.Wall} />
      </group>
    </group>
  )
}

useGLTF.preload('/PyramidTextured-transformed.glb')
