/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 out.glb 
*/

import { useGLTF } from '@react-three/drei';

export function Pyramid(props: any) {
	const { meshes, materials } = useGLTF('./public/pyramid.glb');
	return (
		<group {...props} dispose={null}>
			<group scale={31.515}>
				<mesh
					geometry={meshes.Cube001.geometry}
					material={materials.Brick}
				/>
				<mesh
					geometry={meshes.Cube001_1.geometry}
					material={materials.Sand}
				/>
			</group>
		</group>
	)
}

useGLTF.preload('/out.glb');